---
title: "Chi square Test"
author: "Jason Joseph"
date: "October 23, 2015"
output: html_document
---
```{r Echo=FALSE}
require(dplyr)
require(stringr)
```

"https://raw.githubusercontent.com/fangseup88/IS607_Project3/gh-pages/Data/project_view_1981_2014.csv"

"https://raw.githubusercontent.com/mkds/IS607_Project3/gh-pages/Data/project_view_year_numeric_CLEANED.csv"


```{r}
#load csv
file <- read.csv("https://raw.githubusercontent.com/fangseup88/IS607_Project3/gh-pages/Data/project_view_1981_2014.csv")
head(file)
# clean up white spaces from columns
file$Nominee <- gsub("^\\s+|\\s+$", "", file$Nominee)
file$Category <- gsub("^\\s+|\\s+$", "", file$Category)
file$Won <- gsub("^\\s+|\\s+$", "", file$Won)
file$Nominee <- str_replace(file$Nominee,"'","")


# Construct output  df with distinct categories and their total
output <- count(file,Category)
colnames(output)[2] <- "category_nomination"

# add category won  column
best_picture_nominee <- subset(file, Category == "BEST PICTURE") %>% select(Nominee,Won)
for(i in 1: nrow(output))
{
  #calculate 
  output$won_category[i] <-  subset(file, Category == output$Category[i]) %>%  select(Won) %>%  filter(Won != 'no')%>% nrow
  cat_nominee <- subset(file, Category == output$Category[i]) %>% select(Nominee) 
  output$bp_nomination[i] <- inner_join(cat_nominee,best_picture_nominee,by="Nominee") %>%  nrow()
  output$bp_won[i] <- inner_join(cat_nominee,best_picture_nominee,by="Nominee") %>%  select(Won) %>%  filter(Won != 'no')%>% nrow
  output$bp_lost[i] <- inner_join(cat_nominee,best_picture_nominee,by="Nominee") %>%  select(Won) %>%  filter(Won == 'no')%>% nrow
}
output
```
#Observed Frequencies
```{r}
observed_freq <- output %>% select(Category,bp_won,category_nomination)
observed_freq$Total <- observed_freq$bp_won + observed_freq$category_nomination
observed_freq$percentage <- observed_freq$bp_won/observed_freq$Total
#colnames(observed_freq) <- c("Row variable (Nominated)","Won Best Picture","Nominated for Row Variable","Total","% Best Picture wins")
observed_freq
```

#Expected Frequencies

```{r}
exp_freq <- observed_freq %>% select(Category)
sum_won_best_picture <- sum(observed_freq$bp_won)
sum_category_nomination <- sum(observed_freq$category_nomination)
sum_total <- sum(observed_freq$Total)
for(i in 1:nrow(exp_freq))
{
  val <- observed_freq %>% subset(Category == exp_freq$Category[i])
  exp_freq$bp_won[i] <- val$Total * (sum_won_best_picture / sum_total)
  exp_freq$category_nomination[i] <- val$Total * (sum_category_nomination / sum_total)
}
exp_freq$Total <-  exp_freq$bp_won +  exp_freq$category_nomination
exp_freq
```


#Chi-Sqaure analysis - Angus Huang
#Calculating Chi-Sqaure test to see the if there is any significant difference across the category. As p-value is less than 0.05 (0.02623 & 0.008 as shown below), we can conclude there is significant difference across the category of best pictures won. 

```{r}
library (tidyr)
library (reshape2)


n3data <- output [,c("Category","won_category","bp_won")]
n3data
n4data <-t(n3data)
n5data <- (n4data[2:3,1:11])
n5data <- matrix(as.numeric(unlist(n5data)),nrow = nrow(n5data))
colnames(n5data) <-c("LeadActor", "SupportActor","LeadActress","SupportActress","Best_Picture","Cinematograph","Costume_Design","Directing","Editing","sounds_Editing","Sounds_Mixing")

row.names (n5data) <- c("won_category", "bp_won")


ndata <- output [, c("won_category","bp_won")]


n2data <-output [,c("category_nomination","bp_won")]

pdata <- output [,c("Category","category_nomination","won_category","bp_won")]
pdata
barplot(n5data,beside = T, legend=T)
chisq.test(ndata)
chisq.test(n2data)


```


